version: 2
jobs:
    process-and-publish:
        docker:
            - image: klakegg/hugo:0.107.0-ext-ubuntu
        steps:
            - run:
                  name: Installation des prérequis
                  command: |
                      apt-get update && apt-get install -y lftp
            - run:
                  # Récupération du code manuel car soucis avec "- checkout"
                  name: Récupération de sls-web
                  command: |
                      mkdir -p /home/circleci/project
                      cd /home/circleci/project
                      git clone https://github.com/strainel/sls-web
                      cd sls-web
                      git checkout $CIRCLE_BRANCH
                      git submodule update --init --recursive
            - run:
                  name: Création du site
                  command: |
                       cd /home/circleci/project/sls-web
                       hugo
            - run:
                  name: Publication du site
                  command: |
                      cd /home/circleci/project/sls-web
                      mkdir ~/.ssh/ && echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
                      lftp sftp://${DEPLOY_USER}:${DEPLOY_PASSWORD}@${DEPLOY_HOST} -e "mirror -R public/ public ; quit"
workflows:
    version: 2
    dev:
        jobs:
            - process-and-publish
